name: 'product_manager_planner'
description: 'product_manager_planner'
metadata:
  type: 'PLANNER'
  module: 'HITL_Project.app.core.planner.default.product_manager_planner'
  class: 'ProductManagerPlanner'